### ISSUE TITLE
How do i run this Location Manager library  with Fragments..?

### ISSUE THREAD

**Issue by rubinnellikunnathu** [yayaa/LocationManager#15]
Hello Yaya ,
i tried your sample code in an activity and it worked awesome, I liked it very much and its so easier to use.
But my problem is how do i implement this library in a fragment.?
Can u pls help me.?

**Comment by yayaa** [comment]
I have plans to update library in order it to be more flexible and customizable, but right now it is tightly related with Activity (because displaying dialog, going settings and coming back, listening the result, and so on).

What you could do basically: You can get location in activity and create a method in your fragment and pass received location to the fragment.

**Comment by rubinnellikunnathu** [comment]
thank u i will do as u say..
