### ISSUE TITLE
Rational Message hiding ?

### ISSUE THREAD

**Issue by pmsferreira** [yayaa/LocationManager#16]
Hi,

There is some option to hide rational message when requesting permissions?
I want to show only default app dialog to enable/disable permissions.

Best regards,
Pedro Ferreira

**Comment by yayaa** [comment]
Well, currently that's not possible :) Since Google ask you to show it and the [PermissionManager](https://github.com/yayaa/LocationManager/blob/master/library/src/main/java/com/yayandroid/locationmanager/helper/PermissionManager.java) is their implementation, i didn't make it optional. But yes, it can be implemented.

In these days, i actually have no time to do that changes, but if you are willing to create PR by adding that field into LocationConfiguration and passing that option to PermissionManager, i would gladly review and accept it :) 

In any case, i'll put it as enhancement, so that next time i can implement it, thanks.

**Comment by yayaa** [comment]
Now it is possible with 1.1.5 release, if you don't set rationalMessage then rational dialog will not be displayed at all, and will ask directly for permission.
