### ISSUE TITLE
SettingsApi

### ISSUE THREAD

**Issue by yankeppey** [yayaa/LocationManager#3]
Hey, thanks for the library!
Are there any plans to include SettingsApi from Google Play Services in future release?
https://developers.google.com/android/reference/com/google/android/gms/location/SettingsApi
http://i.stack.imgur.com/x1I7n.jpg

**Comment by yayaa** [comment]
Thanks for leading me to this, i wasn't aware of it yet. I may implement it in future releases, yes. 
But i guess before i develop any more with GooglePlayServices API, i am going to wait until [this issue][1] is resolved, because it leaks.

[1]: https://github.com/googlesamples/android-play-location/issues/26

**Comment by rajeevjaiswal** [comment]
It will be great if settingsAPi is included in the library

**Comment by yayaa** [comment]
Implemented within v1.1.1 release.
