### ISSUE TITLE
How get location when app close or not active?

### ISSUE THREAD

**Issue by no-cat-no** [yayaa/LocationManager#39]
I'm using BroadcastReceiver (see: [SampleService](https://github.com/yayaa/LocationManager/blob/master/app/src/main/java/com/yayandroid/locationmanager/sample/service/SampleService.java)). However, when the application is closed or inactive (enabled, but running in the background), the coordinates are not determined. I tried to comment out the line with unregisterReceiver, but it did not help.

```java
@Override
protected void onPause() {
    super.onPause();
//    unregisterReceiver(broadcastReceiver);
}
```

**Comment by yayaa** [comment]
Hey, @no-cat-no that is an implementation detail, **not an issue of this library**. 

If your app needs to be behave even it's on background, then you might need to consider re-launching or implementing your own login within the service instead of using broadcast receiver to notify some part of the application.

**Comment by no-cat-no** [comment]
I'm sorry, you're right. I'm not a very good programmer, so many questions.
