### ISSUE TITLE
How can i stop location listener after i getting my location at first time.

### ISSUE THREAD

**Issue by SkyNite** [yayaa/LocationManager#4]
Hi @yayaa, thanks for this library, here i need to get user  current location only once. Can you assist me to achieve this.

**Comment by yayaa** [comment]
Please do not open your questions as issue! you may send me an email, this is not the way.

Still, library is already design to get location only once. If you want to keep getting updates you need to specify keepTracking(true) otherwise it will removeUpdates once it gets location.

Check [configuration file](https://github.com/yayaa/LocationManager/blob/master/Library/app/src/main/java/com/yayandroid/locationmanager/LocationConfiguration.java) for more information.
