### ISSUE TITLE
same location in different places

### ISSUE THREAD

**Issue by ghizoo** [yayaa/LocationManager#72]
Sometime i get the same coordinates in different places using this library

**Comment by rmtheis** [comment]
You didn't leave any details, but you're likely seeing the "last known" location. Try using `.ignoreLastKnowLocation(false)`

**Comment by yayaa** [comment]
Yes, please consider to update description by following up the [issue template](https://github.com/yayaa/LocationManager/blob/master/.github/issue_template.md).

@rmtheis is right, either you can set `ignoreLastKnowLocation(true)` so that manager requests location updates anyway or try to reduce your time interval configurations.
