### ISSUE TITLE
LocationManager is not able to retrieve location on a device without Google Mobile Services and without GPS. 

### ISSUE THREAD

**Issue by smarly** [yayaa/LocationManager#98]
LocationManager is not able to retrieve location on a device without Google Mobile Services and without GPS. 
Can LocationManager.NETWORK_PROVIDER really work without GMS ?
### Configuration
Sample app

### Logs
2019-11-20 11:57:54.807 27128-27128/com.yayandroid.locationmanager.sample I/DefaultLocationProvider: User didn't want to enable GPS, so continue with Network Provider
2019-11-20 11:57:54.809 27128-27128/com.yayandroid.locationmanager.sample I/DefaultLocationProvider: Network is not enabled, calling fail...

**Comment by yayaa** [comment]
There is nothing that the library can do here, since "Network is not enabled" is a sign that [Platform's LocationManager](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/location/java/android/location/LocationManager.java) indicates that Network provider is not enabled. 

For that, you can check stackoverflow - there are quite some question regarding to that. 
I'll close this for now, but feel free to re-open if you find anything that is related to this library.
